routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//register
// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');
//endregister

//login
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

//cronjob
Route::get('execution/{id}', 'Cronjob\CronjobController@execution')->name('execution');
Route::prefix('cronjob_list')->name('cronjob_list.')->group(function () {
    // $name = 'cronjob_list.';
    // Route::get('getdataproduct', 'Api\Imo\ImoController@getdataproduct')->name('getdataproduct');
    Route::get('getstokcpointvendor', 'Zone\ZoneController@getstokcpointvendor')->name('getstokcpointvendor');
    Route::get('getstockpointcoveragevendor', 'Zone\ZoneController@getstockpointcoveragevendor')->name('getstockpointcoveragevendor');
    
    // Route::get('getdatavendor', 'Api\Imo\ImoController@getdatavendor')->name('vendor.getdatavendor')
    Route::get('getdatavendor', 'Api\Imo\ImoController@getdatavendor')->name('getdatavendor');
    Route::get('getdatacustomer', 'Api\Imo\ImoController@getdatacustomer')->name('getdatacustomer');
    Route::get('getdataorder', 'Api\Imo\ImoController@getdataorder')->name('getdataorder');
    Route::get('postdatacustomer', 'Api\Imo\ImoController@postdatacustomer')->name('postdatacustomer');
    Route::get('postdataproduct', 'Api\Imo\ImoController@postdataproduct')->name('postdataproduct');
    Route::get('postdataprice', 'Api\Imo\ImoController@postdataprice')->name('postdataprice');
    Route::get('postdatastock', 'Api\Imo\ImoController@postdatastock')->name('postdatastock');
    Route::get('postdataorder', 'Api\Imo\ImoController@postdataorder')->name('postdataorder');
    Route::get('getdataproduct', 'Api\Imo\ImoController@getdataproduct')->name('getdataproduct');
    Route::get('getdataproductinactive', 'Api\Imo\ImoController@getProductInactive')->name('getdataproductinactive');
    Route::get('postdataproductinactive', 'Api\Imo\ImoController@postProductInactive')->name('postdataproductinactive');
    Route::get('getdataproductbtn', 'Api\Imo\ImoController@getdataproductbtn')->name('getdataproductbtn');
    Route::get('getdataprice', 'Api\Imo\ImoController@getdataprice')->name('getdataprice');
    Route::get('getdatastock', 'Api\Imo\ImoController@getdatastock')->name('getdatastock');
    Route::get('getmwstatus', 'Api\Imo\ImoController@getmwstatus')->name('getmwstatus');
    Route::get('postmwstatus', 'Api\Imo\ImoController@postmwstatus')->name('postmwstatus');
    Route::get('getorderstatus', 'Api\Imo\ImoController@getorderstatus')->name('getorderstatus');
    Route::get('postorderstatus', 'Api\Imo\ImoController@postorderstatus')->name('postorderstatus');
    Route::get('getordertracking', 'Api\Imo\ImoController@getordertracking')->name('getordertracking');
    Route::get('postordertracking', 'Api\Imo\ImoController@postordertracking')->name('postordertracking');
    Route::get('Createrevision', 'Api\Imo\ImoController@Createrevision')->name('createrevision');
    Route::get('pushrevision', 'Api\Imo\ImoController@pushRevision')->name('pushrevision');
    Route::get('get_orderresuffle', 'Api\Imo\ImoController@get_orderresuffle')->name('get_orderresuffle');
    Route::get('clearlog', 'Api\Imo\ImoController@clearlog')->name('clearlog');
});
//cronjob


//endlogin
Route::middleware(['acl'])->group(function () {

Route::prefix('merchant')->group(function() {
    Route::get('/', 'Merchant\MerchantSetupController@show')->name('merchant.show');
    Route::post('/store', 'Merchant\MerchantSetupController@store')->name('merchant.store');
    Route::put('/{id}', 'Merchant\MerchantSetupController@update')->name('merchant.update');
});

//acl
Route::prefix('user')->group(function () {
    Route::get('/', 'User\UserController@index')->name('user.index');
    Route::post('/store', 'User\UserController@store')->name('user.store');
    Route::get('{id}/edit', 'User\UserController@edit')->name('user.edit');
    Route::put('{id}', 'User\UserController@update')->name('user.update');
    Route::get('/user-list', 'User\UserHelper@userlist')->name('user.user-list');       
});

Route::prefix('usergroups')->group(function () {
    Route::get('/', 'User\UserGroupsController@index')->name('usergroups.index');
    Route::post('/store', 'User\UserGroupsController@store')->name('usergroups.store');
    Route::get('{id}/edit', 'User\UserGroupsController@edit')->name('usergroups.edit');
    Route::put('{id}', 'User\UserGroupsController@update')->name('usergroups.update');
    Route::get('/data-list', 'User\UserGroupsHelper@datalist')->name('usergroups.usergroups-list');     
});
//endacl

Route::get('/', 'Cronjob\CronjobController@index')->name('index.customer');
// Route::get('/', function () {
//     return redirect()->route('cronjob.setup');
//     // return view('cronjob.index');
// });

// Auth::routes();

Route::get('/test', function(){
    $class = new \App\Http\Controllers\Vendor\VendorService;
    return $class->getstockpoint();
});

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('cronjob', 'Cronjob\CronjobController')->except([
    'destroy', 'show'
]);
Route::get('cronjob-setup', 'Cronjob\CronjobController@setup')->name('cronjob.setup');

Route::prefix('imoidmarco')->name('api.imo.')->group(function () {
    Route::get('getdataproduct', 'Api\Imo\ImoController@getdataproduct')->name('getdataproduct');
    Route::get('getdatavendor', 'Api\Imo\ImoController@getdatavendor')->name('getdatavendor');
    Route::get('getdatacustomerbtn', 'Api\Imo\ImoController@getdatacustomerbtn')->name('getdatacustomerbtn');
    // Route::get('getdatavendorbtn', 'Api\Imo\ImoController@getdatavendorbtn')->name('getdatavendorbtn');
});


Route::prefix('master')->name('master.')->group(function () {
	Route::get('vendor', 'Vendor\VendorController@index')->name('vendor');
	Route::get('vendor-update/{id}', 'Vendor\VendorController@update')->name('vendor.update');
	Route::post('vendor-store/{id}', 'Vendor\VendorController@simpan')->name('vendor.store');
	
	Route::get('ajaxvendor', 'Vendor\VendorController@ajaxvendor')->name('ajaxvendor.datatables');
});

Route::prefix('transaction')->name('transaction.')->group(function () {
    Route::get('product', 'Product\ProductController@index')->name('product');
    Route::get('inventory', 'Inventory\InventoryController@index')->name('inventory');
    Route::get('zones', 'Zone\ZoneController@index')->name('zone.index');
    Route::get('price', 'Price\PriceController@index')->name('price.index');
});

Route::get('apilist', 'Api\APIController@index')->name('api.list');
Route::get('addnewapi', 'Api\APIController@create')->name('api.create');

Route::prefix('datatables')->name('datatables.')->group(function () {
    Route::get('getstockpoint', 'Zone\ZoneController@getstockpoint')->name('getstockpoint');
});


Route::get('ordertoktok', 'Order\OrderController@indextoktok')->name('order.index');

Route::get('customer', 'Customer\CustomerController@index')->name('index.customer');
Route::get('btngetstockpointvendor', 'Zone\ZoneController@btngetstockpointvendor')->name('btngetstockpointvendor');
Route::get('btngetstockpointcoveragevendor', 'Zone\ZoneController@btngetstockpointcoveragevendor')->name('btngetstockpointcoveragevendor');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
});
// Auth::routes();

app/Models/Price.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Price extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Price/PriceController.php
<?php

namespace App\Http\Controllers\Price;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Price;
use DataTables;

class PriceController extends Controller
{
    public function index(Request $request)
    {
    	if($request->ajax())
    	{
	    	$prices = Price::query();		
	    	return DataTables::eloquent($prices)
	    		->editColumn('vendor_price', function(Price $price) {
	    			return number_format($price->vendor_price, 2, ',', '.');
	    		})
	    		->toJson();
    	}
    	return view('price.index');
    }
}

resources/views/price/index.blade.php
@extends('layouts.main')

@push('style')
<link href="{{ asset('template/pages/assets/plugins/pace/pace-theme-flash.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/bootstrap/css/bootstrap.min.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/font-awesome/css/font-awesome.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/jquery-scrollbar/jquery.scrollbar.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/assets/plugins/select2/css/select2.min.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/assets/plugins/switchery/css/switchery.min.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/assets/plugins/jquery-datatable/media/css/dataTables.bootstrap.min.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/datatables-responsive/css/datatables.responsive.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/pages/css/pages-icons.css ') }}" rel="stylesheet" type="text/css">
<link class="main-stylesheet" href="{{ asset('template/pages/pages/css/pages.css ') }}" rel="stylesheet" type="text/css" />
<style type="text/css">
.tengah {
    text-align: center;
}

.notbold {
    font-weight: 500;
}
</style>
@endpush

@section('content')
<div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid   container-fixed-lg sm-p-l-0 sm-p-r-0">
        <div class="inner">
            <!-- START BREADCRUMB -->
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Product</li>
                <li class="breadcrumb-item">Transaction</li>
                <li class="breadcrumb-item active">Inventory</li>
            </ol>
            <!-- END BREADCRUMB -->
        </div>
    </div>
</div>
<!-- START CONTAINER FLUID -->
<div class=" container-fluid container-fixed-lg bg-white">
    <!-- START card -->
    <div class="card card-transparent">
        <div class="col-sm-12" style="text-align: center;"><br><H3>Price</H3></div>
        <div class="card-header d-flex justify-content-between">
          <div class="row">
            
          </div>
        </div>
        <div class="card-body">
            <table class="table" style="width:100%" id="pricetable">
                <thead>
                    <tr>
                        <th class="tengah">Vendor Price</th>
                        <th class="tengah">Valid On</th>
                        <th class="tengah">Last Sync TokTok</th>
                        <th class="tengah">Last Sync Vendor</th>
                        <th class="tengah">SKU</th>
                        <th class="tengah">Kode SP</th>
                        <th class="tengah">Created At</th>
                        <th class="tengah">Updated At</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    <!-- END card -->
</div>
<!-- END CONTAINER FLUID -->
@endsection

@push('scripts')
<!-- BEGIN VENDOR JS -->
<script src="{{ asset('template/pages/assets/plugins/pace/pace.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery/jquery-1.11.1.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/modernizr.custom.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-ui/jquery-ui.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/tether/js/tether.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/bootstrap/js/bootstrap.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery/jquery-easy.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-unveil/jquery.unveil.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-ios-list/jquery.ioslist.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-actual/jquery.actual.min.js ') }}"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js ') }}"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/select2/js/select2.full.min.js ') }}"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/classie/classie.js ') }}"></script>
<script src="{{ asset('template/pages/assets/plugins/switchery/js/switchery.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/media/js/jquery.dataTables.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/media/js/dataTables.bootstrap.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js ') }}" type="text/javascript"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/datatables-responsive/js/datatables.responsive.js ') }}"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/datatables-responsive/js/lodash.min.js ') }}"></script>
<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="{{ asset('template/pages/pages/js/pages.min.js ') }}"></script>
<!-- END CORE TEMPLATE JS -->
<!-- BEGIN PAGE LEVEL JS -->
<script src="{{ asset('template/pages/assets/js/datatables.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/js/scripts.js ') }}" type="text/javascript"></script>
<!-- END PAGE LEVEL JS -->
<script>
    $(document).ready(function() {
        $('#pricetable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{{ route("transaction.price.index") }}',
            columns: [
                { data: 'vendor_price', name: 'vendor_price' },
                { data: 'valid_on', name: 'valid_on' },
                { data: 'lastsynctoktok', name: 'lastsynctoktok' },
                { data: 'lastsyncvendor', name: 'lastsyncvendor' },
                { data: 'sku', name: 'sku' },
                { data: 'kode_sp', name: 'kode_sp' },
                { data: 'created_at', name: 'created_at' },
                { data: 'updated_at', name: 'updated_at' }
            ],
            columnDefs: [
                
            ],
            order: [[7, 'desc']]
        });
    })
</script>
@endpush    