routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//register
// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');
//endregister

//login
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

//cronjob
Route::get('execution/{id}', 'Cronjob\CronjobController@execution')->name('execution');
Route::prefix('cronjob_list')->name('cronjob_list.')->group(function () {
    // $name = 'cronjob_list.';
    // Route::get('getdataproduct', 'Api\Imo\ImoController@getdataproduct')->name('getdataproduct');
    Route::get('getstokcpointvendor', 'Zone\ZoneController@getstokcpointvendor')->name('getstokcpointvendor');
    Route::get('getstockpointcoveragevendor', 'Zone\ZoneController@getstockpointcoveragevendor')->name('getstockpointcoveragevendor');
    
    // Route::get('getdatavendor', 'Api\Imo\ImoController@getdatavendor')->name('vendor.getdatavendor')
    Route::get('getdatavendor', 'Api\Imo\ImoController@getdatavendor')->name('getdatavendor');
    Route::get('getdatacustomer', 'Api\Imo\ImoController@getdatacustomer')->name('getdatacustomer');
    Route::get('getdataorder', 'Api\Imo\ImoController@getdataorder')->name('getdataorder');
    Route::get('postdatacustomer', 'Api\Imo\ImoController@postdatacustomer')->name('postdatacustomer');
    Route::get('postdataproduct', 'Api\Imo\ImoController@postdataproduct')->name('postdataproduct');
    Route::get('postdataprice', 'Api\Imo\ImoController@postdataprice')->name('postdataprice');
    Route::get('postdatastock', 'Api\Imo\ImoController@postdatastock')->name('postdatastock');
    Route::get('postdataorder', 'Api\Imo\ImoController@postdataorder')->name('postdataorder');
    Route::get('getdataproduct', 'Api\Imo\ImoController@getdataproduct')->name('getdataproduct');
    Route::get('getdataproductinactive', 'Api\Imo\ImoController@getProductInactive')->name('getdataproductinactive');
    Route::get('postdataproductinactive', 'Api\Imo\ImoController@postProductInactive')->name('postdataproductinactive');
    Route::get('getdataproductbtn', 'Api\Imo\ImoController@getdataproductbtn')->name('getdataproductbtn');
    Route::get('getdataprice', 'Api\Imo\ImoController@getdataprice')->name('getdataprice');
    Route::get('getdatastock', 'Api\Imo\ImoController@getdatastock')->name('getdatastock');
    Route::get('getmwstatus', 'Api\Imo\ImoController@getmwstatus')->name('getmwstatus');
    Route::get('postmwstatus', 'Api\Imo\ImoController@postmwstatus')->name('postmwstatus');
    Route::get('getorderstatus', 'Api\Imo\ImoController@getorderstatus')->name('getorderstatus');
    Route::get('postorderstatus', 'Api\Imo\ImoController@postorderstatus')->name('postorderstatus');
    Route::get('getordertracking', 'Api\Imo\ImoController@getordertracking')->name('getordertracking');
    Route::get('postordertracking', 'Api\Imo\ImoController@postordertracking')->name('postordertracking');
    Route::get('Createrevision', 'Api\Imo\ImoController@Createrevision')->name('createrevision');
    Route::get('pushrevision', 'Api\Imo\ImoController@pushRevision')->name('pushrevision');
    Route::get('get_orderresuffle', 'Api\Imo\ImoController@get_orderresuffle')->name('get_orderresuffle');
    Route::get('clearlog', 'Api\Imo\ImoController@clearlog')->name('clearlog');
});
//cronjob


//endlogin
Route::middleware(['acl'])->group(function () {

Route::prefix('merchant')->group(function() {
    Route::get('/', 'Merchant\MerchantSetupController@show')->name('merchant.show');
    Route::post('/store', 'Merchant\MerchantSetupController@store')->name('merchant.store');
    Route::put('/{id}', 'Merchant\MerchantSetupController@update')->name('merchant.update');
});

//acl
Route::prefix('user')->group(function () {
    Route::get('/', 'User\UserController@index')->name('user.index');
    Route::post('/store', 'User\UserController@store')->name('user.store');
    Route::get('{id}/edit', 'User\UserController@edit')->name('user.edit');
    Route::put('{id}', 'User\UserController@update')->name('user.update');
    Route::get('/user-list', 'User\UserHelper@userlist')->name('user.user-list');       
});

Route::prefix('usergroups')->group(function () {
    Route::get('/', 'User\UserGroupsController@index')->name('usergroups.index');
    Route::post('/store', 'User\UserGroupsController@store')->name('usergroups.store');
    Route::get('{id}/edit', 'User\UserGroupsController@edit')->name('usergroups.edit');
    Route::put('{id}', 'User\UserGroupsController@update')->name('usergroups.update');
    Route::get('/data-list', 'User\UserGroupsHelper@datalist')->name('usergroups.usergroups-list');     
});
//endacl

Route::get('/', 'Cronjob\CronjobController@index')->name('index.customer');
// Route::get('/', function () {
//     return redirect()->route('cronjob.setup');
//     // return view('cronjob.index');
// });

// Auth::routes();

Route::get('/test', function(){
    $class = new \App\Http\Controllers\Vendor\VendorService;
    return $class->getstockpoint();
});

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('cronjob', 'Cronjob\CronjobController')->except([
    'destroy', 'show'
]);
Route::get('cronjob-setup', 'Cronjob\CronjobController@setup')->name('cronjob.setup');

Route::prefix('imoidmarco')->name('api.imo.')->group(function () {
    Route::get('getdataproduct', 'Api\Imo\ImoController@getdataproduct')->name('getdataproduct');
    Route::get('getdatavendor', 'Api\Imo\ImoController@getdatavendor')->name('getdatavendor');
    Route::get('getdatacustomerbtn', 'Api\Imo\ImoController@getdatacustomerbtn')->name('getdatacustomerbtn');
    // Route::get('getdatavendorbtn', 'Api\Imo\ImoController@getdatavendorbtn')->name('getdatavendorbtn');
});


Route::prefix('master')->name('master.')->group(function () {
	Route::get('vendor', 'Vendor\VendorController@index')->name('vendor');
	Route::get('vendor-update/{id}', 'Vendor\VendorController@update')->name('vendor.update');
	Route::post('vendor-store/{id}', 'Vendor\VendorController@simpan')->name('vendor.store');
	
	Route::get('ajaxvendor', 'Vendor\VendorController@ajaxvendor')->name('ajaxvendor.datatables');
});

Route::prefix('transaction')->name('transaction.')->group(function () {
    Route::get('product', 'Product\ProductController@index')->name('product');
    Route::get('inventory', 'Inventory\InventoryController@index')->name('inventory');
    Route::get('zones', 'Zone\ZoneController@index')->name('zone.index');
    Route::get('price', 'Price\PriceController@index')->name('price.index');
});

Route::get('apilist', 'Api\APIController@index')->name('api.list');
Route::get('addnewapi', 'Api\APIController@create')->name('api.create');

Route::prefix('datatables')->name('datatables.')->group(function () {
    Route::get('getstockpoint', 'Zone\ZoneController@getstockpoint')->name('getstockpoint');
});


Route::get('ordertoktok', 'Order\OrderController@indextoktok')->name('order.index');

Route::get('customer', 'Customer\CustomerController@index')->name('index.customer');
Route::get('btngetstockpointvendor', 'Zone\ZoneController@btngetstockpointvendor')->name('btngetstockpointvendor');
Route::get('btngetstockpointcoveragevendor', 'Zone\ZoneController@btngetstockpointcoveragevendor')->name('btngetstockpointcoveragevendor');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
});
// Auth::routes();

app/Models/Cronjob.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cronjob extends Model
{
    protected $guarded = [];

    public function vendor()
    {
    	# code...
    	return $this->belongsTo("App\Models\Vendor");
    }

    public function cronjoblog()
    {
    	# code...
    	return $this->hasMany("App\Models\CronjobLog");
    }
}

app/Http/Controllers/Cronjob/CronjobController.php
<?php

namespace App\Http\Controllers\Cronjob;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CronjobController extends Controller
{
    //
    public function __construct()
    {
        # code...
        $this->data['everyexpressionvalues'] =
        [
          "* * * * *" => "minute",
          "*/2 * * * *" => "2 minute",
          "*/3 * * * *" => "3 minute",
          "*/4 * * * *" => "4 minute",
          "*/5 * * * *" => "5 minute",
          "*/6 * * * *" => "6 minute",
          "*/10 * * * *" => "10 minute",
          "*/12 * * * *" => "12 minute",
          "*/15 * * * *" => "15 minute",
          "*/20 * * * *" => "20 minute",
          "*/30 * * * *" => "30 minute",
          "0 * * * *" => "hour",
          "0 */2 * * *" => "2 hour",
          "0 */3 * * *" => "3 hour",
          "0 */4 * * *" => "4 hour",
          "0 */5 * * *" => "5 hour",
          "0 */6 * * *" => "6 hour",
          "0 */8 * * *" => "8 hour",
          "0 */12 * * *" => "12 hour",
          "0 0 * * *" => "day",
          "0 0 */2 * *" => "2 day",
          "0 0 */3 * *" => "3 day",
          "0 0 */5 * *" => "5 day",
          "0 0 */10 * *" => "10 day",
          "0 0 */15 * *" => "15 day",
        ];
    }

    public function routelistcront()
    {
        # code...        
        $route    = collect(\Route::getRoutes())->map(function ($route) {
                    return $route->uri();
                });

        $banyak   = count($route);
        $new_data = [];

        for ($i=0; $i < $banyak; $i++) { 
            # code...
            # cronjob_list/
            if(substr($route[$i], 0, 13) == "cronjob_list/"){
                array_push($new_data, $route[$i]);
            }
        }

        return $new_data;
    }

    public function index($value='')
    {
        # code...       
        return view('cronjob.index')->with($this->data);
    }

    public function create($value='')
    {
        # code...
        $this->data["url"]            = route("cronjob.store");
        $this->data["method"]         = "POST";
        $this->data["list_url_cront"] = $this->routelistcront();
         $this->data["log"]            = [];
        return view('cronjob.form.create')->with($this->data);
    }

    public function edit($id)
    {
        # code...
        $this->data["data"]           = \App\Models\Cronjob::find($id);
        $this->data["url"]            = route("cronjob.update", $id);
        $this->data["method"]         = "PUT";
        $this->data["log"]            = \App\Models\CronjobLog::whereCronjob_id($id)->get();
        $this->data["list_url_cront"] = $this->routelistcront();
        return view('cronjob.form.create')->with($this->data);
    }

    public function store(Request $request)
    {
        # code...
        $input  = $request->all();
        
        $store = \App\Models\Cronjob::create([
            'vendor_id' => $input['vendor_id'],
            'name' => $input['name'],
            // 'description' => $input['description'],
            'time_defined' => 0,
            'request_url' => $input['request_url'],            
            'every_expression' => $input['every_expression'],            
            'status' => $input['status'],
            'status_log' => $input['status_log'],
        ]);

        $setcron = \App\Http\Controllers\Cronjob\CronjobHelper::setcron();

        return redirect()->route('cronjob.index');
    }

    public function update(Request $request, $id)
    {
    	# code...
        $input  = $request->all();
    	
        $store = \App\Models\Cronjob::updateOrCreate(
            [
                'id' => $id,
            ],
            [
            'vendor_id' => $input['vendor_id'],
            'name' => $input['name'],
            // 'description' => $input['description'],
            'time_defined' => 0,
            'request_url' => $input['request_url'],            
            'every_expression' => $input['every_expression'],            
            'status' => $input['status'],
            'status_log' => $input['status_log'],
        ]);

        $setcron = \App\Http\Controllers\Cronjob\CronjobHelper::setcron();

        return redirect()->route('cronjob.index');
    }

    public function setup(){
        return view('cronjob.form.setup');
    }

    public function execution($id)
    {
        # code...
        $logger  = ['cronjob_id' => $id, 'start_time' => date('Y-m-d H:i:s')];
        $findurl = \App\Models\Cronjob::find($id);
        $ch      = curl_init();
        $url     = "$findurl->request_url";

        $ch  = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept: application/json', 'Content-Type: application/json'));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);        
        $result      = curl_exec($ch);
        $result_info = curl_getinfo($ch);
        // $location = json_decode($server_output, false);
        curl_close($ch);

        $logger['http_code']     = $result_info['http_code'];
        $logger['connect_time']  = round($result_info['connect_time'], 3);
        $logger['total_time']    = round($result_info['total_time'], 3);
        $logger['end_time']      = date('Y-m-d H:i:s');
        $logger['output_length'] = $result_info['size_download'];
        $logger['return_value']  = $result;

        if($findurl->status_log == 1){

            $storehistory = \App\Models\CronjobLog::create([

                'cronjob_id' => $id,
                'message' => $logger['return_value'],
                'status' => $logger['http_code'],
                'last_sync' => date('Y-m-d H:i:s'),
            ]);
        }

        return $logger;

    }
}

app/Http/Controllers/Cronjob/CronjobHelper.php
<?php

namespace App\Http\Controllers\Cronjob;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CronjobHelper extends Controller
{

    public static function setcron($value='')
    {
    	# code...
    	$user_crontab = "www-data";
    	$filename_temp_gen = false;
    	$current_dir = __DIR__;    	
    	$temp_storage_dir = storage_path() . "/framework/cache/";
    	$filename_temp = !$filename_temp_gen ? "00000000000000_cronjob" : date('YmdHis') . "_cronjob";

    	
    		/* load cronjobs */
    		$cronjobs = \App\Models\CronJob::whereStatus(1)->orderBy('id')->get();

    		/* new / open file stream */
    		$f = fopen("$temp_storage_dir/$filename_temp", "w");
    		$begin = "#Shell variable for cron\nSHELL=/bin/bash\n\n#PATH variable for cron\nPATH=/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin:/usr  /bin/X11\n\n#Job List\n";
    		fwrite($f, $begin);

    		/* load expression from data base */    		
    		$result_data = "";
    		$text_expression = "";

    		foreach($cronjobs as $cronjob) {

                $url = route("execution", $cronjob->id);
                $result_data .= "$cronjob->every_expression curl $url\n";
    		}

    		fwrite($f, $result_data);

    		/* close / save file stream */
    		fclose($f);

    		/* after build, add list to crontab */
    		// clear all crontab
    		$cmd1 = exec("crontab -r -u ".$user_crontab);

    		// // set crontab list
    		$cmd2 = exec("crontab $temp_storage_dir/$filename_temp -u ".$user_crontab);
    }
}

resources/views/cronjob/index.blade.php
@extends('layouts.main')

@push('style')
<link href="{{ asset('template/pages/assets/plugins/pace/pace-theme-flash.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/bootstrap/css/bootstrap.min.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/font-awesome/css/font-awesome.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/jquery-scrollbar/jquery.scrollbar.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/assets/plugins/select2/css/select2.min.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/assets/plugins/switchery/css/switchery.min.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/assets/plugins/jquery-datatable/media/css/dataTables.bootstrap.min.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css ') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('template/pages/assets/plugins/datatables-responsive/css/datatables.responsive.css ') }}" rel="stylesheet" type="text/css" media="screen" />
<link href="{{ asset('template/pages/pages/css/pages-icons.css ') }}" rel="stylesheet" type="text/css">
<link class="main-stylesheet" href="{{ asset('template/pages/pages/css/pages.css ') }}" rel="stylesheet" type="text/css" />
@endpush

@section('content')

<div class="jumbotron" data-pages="parallax">
  <div class=" container-fluid   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="inner">
      <!-- START BREADCRUMB -->
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Cronjob</li>
      </ol>
      <!-- END BREADCRUMB -->      
    </div>
  </div>
</div>

<!-- START CONTAINER FLUID -->
<div class=" container-fluid   container-fixed-lg bg-white">
  <!-- START card -->
  <div class="card card-transparent">
    <div class="col-sm-12" style="text-align: center;"><br><H3>Cronjob List</H3></div>
    <div class="card-header  d-flex justify-content-between">
      <a class="btn btn-complete btn-cons" href="{{route("cronjob.create")}}">Create new</a>
      <div class="export-options-container"></div>
      <!-- <div class="clearfix"></div> -->
    </div>
    <div class="card-block">
      <table class="table table-striped" id="tableWithExportOptions">
        <thead>
          <tr>
            <th>ID</th>
            <th>Vendor Name</th>
            <th>API Name</th>
            <th>API URL</th>
            <th>Last sync</th>
            <th>Execute every</th>
            <th>Cronjob status</th>
          </tr>
        </thead>

        <tbody>
          @foreach(\App\Models\Cronjob::get() as $row)
          <tr>
            <td><a href="{{route("cronjob.edit", $row->id)}}">{{$row->id}}</a></td>
            <td>{{$row->vendor->vendor_name}}</td>
            <td>{{$row->name}}</td>
            <td>{{$row->request_url}}</td>
            <td>{{$row->cronjoblog()->orderBy("id", "desc")->first()->created_at ?? "0000-00-00 00:00:00"}}</td>
            <td>{{$everyexpressionvalues[$row->every_expression]}}</td>
            <td>{{$row->status == 1 ? "active" : "disactive"}}</td>
          </tr>
          @endforeach
        </tbody>
        
      </table>
    </div>
  </div>
  <!-- END card -->
</div>
<!-- END CONTAINER FLUID -->

@endsection

@push('scripts')
<!-- BEGIN VENDOR JS -->
<script src="{{ asset('template/pages/assets/plugins/pace/pace.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery/jquery-1.11.1.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/modernizr.custom.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-ui/jquery-ui.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/tether/js/tether.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/bootstrap/js/bootstrap.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery/jquery-easy.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-unveil/jquery.unveil.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-ios-list/jquery.ioslist.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-actual/jquery.actual.min.js ') }}"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js ') }}"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/select2/js/select2.full.min.js ') }}"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/classie/classie.js ') }}"></script>
<script src="{{ asset('template/pages/assets/plugins/switchery/js/switchery.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/media/js/jquery.dataTables.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/media/js/dataTables.bootstrap.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js ') }}" type="text/javascript"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/datatables-responsive/js/datatables.responsive.js ') }}"></script>
<script type="text/javascript" src="{{ asset('template/pages/assets/plugins/datatables-responsive/js/lodash.min.js ') }}"></script>
<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="{{ asset('template/pages/pages/js/pages.min.js ') }}"></script>
<!-- END CORE TEMPLATE JS -->
<!-- BEGIN PAGE LEVEL JS -->
<script src="{{ asset('template/pages/assets/js/datatables.js ') }}" type="text/javascript"></script>
<script src="{{ asset('template/pages/assets/js/scripts.js ') }}" type="text/javascript"></script>
<!-- END PAGE LEVEL JS -->
@endpush